package com.example.eye

enum class ScreeningPhase {
    ALIGN_FRONT,

    REFLECTION_BACK_PREPARE,
    REFLECTION_BACK_CAPTURE,

    COVER_RIGHT_PREPARE,
    COVER_RIGHT_COVER_1,
    COVER_RIGHT_UNCOVER_1,
    COVER_RIGHT_COVER_2,
    COVER_RIGHT_UNCOVER_2,

    COVER_LEFT_PREPARE,
    COVER_LEFT_COVER_1,
    COVER_LEFT_UNCOVER_1,
    COVER_LEFT_COVER_2,
    COVER_LEFT_UNCOVER_2,

    RESULT
}